[package]
name = "lgn-messages"
version = "1.0.1"
edition = "2021"

[dependencies]
alloy-primitives = { version = "0.7.7", default-features = false, features = ["serde"] }
alloy-serde = "0.2.1"
anyhow = { version = "1.0.86" }
derive-debug-plus = { version = "0.5.0" }
ethers = { version = "2.0.14" }
object_store = { version = "0.10" }
serde = { version = "1.0.202" }
serde_derive = { version = "1.0.202" }
serde_json = { version = "1.0.117" }
thiserror = { version = "1.0.61" }

mp2_common.workspace = true
mp2_v1.workspace = true
verifiable-db.workspace = true
